Repository LikeLion11th-SY-Team/nong-min, pull requests merged in 2023-08, with the labels that each got.

#5 [FEAT] 카카오 로그인 구현 (#1)
  .gitignore
  package-lock.json
  package.json
  public/Image/kakao_login_medium_narrow.png
  src/App.js
  src/Component/LoginHandler.js
  src/Component/SignUp.js
  src/View/Login.js
Labels: FEAT, 재혁

#8 [FEAT] 회원가입 폼 구성 (#6)
  .gitignore
  public/images/kakao_login_medium_narrow.png
  src/Component/LoginHandler.js
  src/View/Login.js
  src/View/SignUp.js
Labels: FEAT, 재혁

#11 [FEAT] 랜딩 페이지 및 홈 화면 구현 (#3) (#4)
  public/images/community.png
  public/images/home.png
  public/images/practice.png
  public/images/practice2.png
  src/App.css
  src/App.js
  src/Component/NavBar.js
  src/Main/Board.css
  src/Main/Board.js
  src/Main/NavBar/NavBar.css
  src/Main/NavBar/NavBar.js
  src/View/Home.js
  src/View/Landing.js
  src/close.svg
Labels: FIX, 주원

#12 [FEAT] API 연결 (#6)(#11)
  src/View/Login.js
  src/View/SignUp.js
Labels: FEAT, FIX, 재혁

#21 [FEAT] 토글 기능 구현 (#17)
  public/images/kakao_login_large_wide 1.png
  src/App.js
  src/Component/Login.js
  src/Component/LoginHandler.js
  src/Component/SignUp.js
  src/View/Sign.js
Labels: UI, FEAT, FIX, 재혁

#15 [FEAT] 마이페이지 및 커뮤니티 사이드 메뉴바 구현 (#13)
  src/App.js
  src/Component/Login.js
  src/Component/NavBar.js
  src/Component/SignUp.js
  src/MyPage/MyPageEdit.js
  src/MyPage/SideMenu.js
  src/View/Community.js
  src/View/Landing.js
  src/View/MyPage.js
  src/View/Sign.js
Labels: UI, FEAT, 주원

#24 [FEAT] 회원가입 및 로그인 테스트 완료 (#10)(#6)
  src/Component/Login.js
  src/Component/SignUp.js
Labels: FIX

#26 [FIX] 쿠키 통한 토큰 전달 (#9)
  src/Community/PostForm.js
Labels: FIX, 재혁

#30 [FIX] 글 작성 기능 테스트 완료 (#9)
  src/App.js
  src/Community/CommunityBoard.js
  src/Community/PostCard.js
  src/Community/PostForm.js
  src/Component/LoginHandler.js
  src/View/Community.js
Labels: FIX, 재혁

#32 [FEAT] 게시글 상세보기 연결(#9)
  src/Community/CommunityBoard.js
  src/Community/DetailCard.js
  src/Community/PostDetail.js
  src/View/Community.js
Labels: FEAT, 재혁
