Repository LikeLion11th-SY-Team/nong-min, pull requests merged in 2023-12, with the labels that each got.

#36 [ADD] 게시글 미리보기 css 수정, 날짜 format 지정
  .env
  package-lock.json
  package.json
  public/.env
  src/Community/CommunityBoard.js
  src/Community/DetailCard.js
  src/Community/PostCard.js
  src/Component/LoginHandler.js
  src/Component/NavBar.js
  src/Component/SignUp.js
Labels: UI, FEAT, FIX, 재혁

#37 [FIX] 네브바 로그인, 로그아웃 기능 수정 및 학습하기 로그 CSS 수정
  public/images/tutor.png
  public/images/view_alert_id.png
  public/images/view_alert_nickname.png
  public/images/view_home.png
  public/images/view_login.png
  public/images/view_signup.png
  public/images/view_signup2.png
  src/App.js
  src/Component/Login.js
  src/Component/NavBar.js
  src/MyPage/SideMenu.js
  src/Practice/Exercise.js
  src/Practice/Explanation.js
  src/Practice/Log.js
  src/Practice/NextBtn.js
  src/Practice/PracticeMenu.js
  src/Practice/StatusBar.js
  src/Practice/Step0.js
  src/Practice/Step1.js
  src/Practice/Step2.js
  src/Practice/Step3.js
Labels: FEAT, FIX, 주원

#38 [UI] 댓글 작성창 CSS(#9)
  src/Community/DetailCard.js
Labels: UI, 재혁

#39 [FEAT] 서비스 소개 페이지 구현 및 학습하기 수정
  src/App.js
  src/Community/PostForm.js
  src/Component/Login.js
  src/Component/NavBar.js
  src/Component/SignUp.js
  src/MyPage/MyPageEdit.js
  src/Practice/Exercise.js
  src/Practice/Explanation.js
  src/Practice/NextBtn.js
  src/Practice/Step2.js
  src/Practice/Step4.js
  src/View/AboutUs.js
  src/View/Community.js
  src/View/Practice.js
  src/View/Sign.js
Labels: FEAT, FIX, 주원
